### ISSUE TITLE
Black screen on galaxy note 3 sn900 (mali) with lollipop

### ISSUE THREAD

**Issue by ChristopheAlonso** [alanwoolley/CorsixTH-Android#103]
Black screen on launch (after pointing to game directory) happening with galaxy note 3 SN900 (mali) with lollipop (no root) even with the demo. but i'm able to open the menu by clicking the screen randomly and access: setup wizard/settings. Unfortunatly changing resolution or enything else is not helping...

**Comment by alanwoolley** [comment]
Duplicate of #85
