### ISSUE TITLE
Objects flickering on bottom half of map.

### ISSUE THREAD

**Issue by RedZombieHD** [alanwoolley/CorsixTH-Android#111]
[Youtube video](https://youtu.be/ay-Z4xMfqIY)

Using Lenovo Tab2 A10-70 on Android 5.0.1
Happens on full version and demo version in the same way.
Bug happens on 0.9.2 and 0.9.3 alpha.
As you can see by the video it only does it on the bottom half of the map.

**Comment by alanwoolley** [comment]
Thank for the report. I'm not sure what's causing this at the moment and I haven't seen it myself yet. Are you running the stock version of Android or are there modifications to it?

**Comment by RedZombieHD** [comment]
Its stock but im not sure if lenovo made changes to the OS though.
