### ISSUE TITLE
Everything is red - Galaxy S3 4.3, GOG game version

### ISSUE THREAD

**Issue by Farahslax** [alanwoolley/CorsixTH-Android#112]
During first-time startup, the normally-black background of the intro picture (with the Doctor/Nurses' faces centre-screen) flickered red a couple of times, and the main menu was all various shades of red and orange - not the usual lavender. I looked around in the settings menus to see if there was anything to alter this, then decided to try to send feedback. Because I use hotmail and not the built-in email service on my phone, I had to back out and return to the main menu, which then became completely red with bits of the feedback screen flickering in the centre. Then it crashed and prompted an error report.

**Comment by alanwoolley** [comment]
Where are your game files from? Can you reproduce with the demo files?

**Comment by Farahslax** [comment]
The files are from my Win7 desktop, the GOG version of the full game - I followed the full instructions after unlocking dev mode on my phone, which was the only way to enable the files to be read for the game's installation.

I get the same issue after downloading and installing the demo files. I've tried to take screenshots on my phone, but every time I do, the colours show up as normal - not reds and oranges.

**Comment by Kroktar** [comment]
Hi, this is really old but im having this issue now.

I used to play a lot on my Samsung Note 3 on Kitkat but i upgraded to Samsung S9+ and theme Hospital is all red now...you can still see everything but with a red filter.

What i noticed is when i "all tab" or change to another app in android  i can see the game has normal colours when you are scrolling on your open apps but once you click it and it goes to full screen it returns to red.

I hope you can do something :( theme hospital is a game that i always return.

Thanks!

**Comment by alanwoolley** [comment]
I'm going to close this because it's an old issue and I suspect that the recent updates to the SDL library have fixed it. Will happily reopen if it can be replicated on the new snapshot builds.
