### ISSUE TITLE
CorsixTH version is outdated.

### ISSUE THREAD

**Issue by simonjonnemeth** [alanwoolley/CorsixTH-Android#116]
The developers of CorsixTH have recently released a new build (0.61). Please update. Please re-upload to the Play Store.

**Comment by kiokoman** [comment]
CorsixTH 0.62 is now out please update

**Comment by alanwoolley** [comment]
1.0.0-SNAPSHOT builds have now been upgraded to CorsixTH v0.67.

**Comment by simonjonnemeth** [comment]
> 1.0.0-SNAPSHOT builds have now been upgraded to CorsixTH v0.67.

Wow, that came out of the blue. I was never expecting you to return after all these years. As I was always, I'm here to test.
