### ISSUE TITLE
Can't rotate funiture

### ISSUE THREAD

**Issue by hosDumI** [alanwoolley/CorsixTH-Android#117]
Hello,
I am very happy that I found Corsix TH to play Theme Hospital on my Android Tablet. I installed Corsix TH with my full version Theme Hospital CD and it starts fine.
Sadly I am not able to rotate the furniture. I can move it around and can drop it but rotating is not possible. I hold the piece of furniture with one finger and tap on the screen with a second finger (as I have seen it in a youtube video) but nothing happens. The second problem: after about 1 minute (or maybe after I tried to destroy an alredy existing room) I am not able anymore to get the menu for the rooms, moving things, ... I click on the buttons on the left side but no reaction anymore. I have to restart the level then it works fine again.

I use a Samsung Galaxy Tab 3 10.1 Tablet with Android 4.4.2

Maybe you can have a look at my corsix th problems. I am so exicited that I can play Theme Hospital on my Tablet!

Best regards,
Martin

**Comment by simonjonnemeth** [comment]
That's the old but better in my opinion method of rotating items. Now you have to simply tap and hold. I do it where the item can't be placed so it doesn't get placed accidentally.

**Comment by alanwoolley** [comment]
Control scheme has been reworked in v1.0.0. It's still press-and-hold to rotate, but should be much more reliable now.
