### ISSUE TITLE
What is different in released version?

### ISSUE THREAD

**Issue by clementcontet** [alanwoolley/CorsixTH-Android#119]
Hi,

I can see the following permissions added in the released version (http://www.armedpineapple.co.uk/projects/corsixth-for-android/):

    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <uses-permission
        android:name="android.permission.GET_ACCOUNTS" />

    <uses-permission
        android:name="android.permission.USE_CREDENTIALS" />

What are they for?

**Comment by simonjonnemeth** [comment]
I think this is dead now. Alan says he will get back to it eventually but doesn't seem to be rushing.

**Comment by alanwoolley** [comment]
The listed permissions have been removed from all builds.
