### ISSUE TITLE
Can't install the app on Android 14

### ISSUE THREAD

**Issue by davidfa94** [alanwoolley/CorsixTH-Android#134]
Hi there,

Long time ago I had enjoyed this wonderful app on my previous phone, but now I have tried with my Pixel 7 with Android 14 and the Play Store won't let me install it ("Your device is incompatible with this version"). If I extract the app and try to install it locally it doesn't let me either.

Any chance I can get to run it?
Cheers

**Comment by alanwoolley** [comment]
The latest snapshot versions should be compatible with the Pixel 7 and Android 14. Have you joined the beta channel on the play store, or tried the APK from the GitHub releases?

**Comment by davidfa94** [comment]
You were right, joining the beta program was the thing missing. Apologies, and many thanks!
