### ISSUE TITLE
Unicode Languages Problem

### ISSUE THREAD

**Issue by nekkit333** [alanwoolley/CorsixTH-Android#4]
Hi!
In PC Corsix-TH this promlem was fixed, but how fix it in Android ?
Corsix use other font for Unicode, config.txt  has the following lines:

---

-- Font file setting.
-- Specify a font file here if you wish to play the game in a language not
-- present in the original game. Examples include Russian, Chinese and Polish.
## unicode_font = [[X:\ThemeHospital\font.ttc]] 

unicode_font = [[X:\ThemeHospital\font.ttc]]  - path to font in Windows.
Graphics.lua   has the following lines:
font_file = windir .. pathsep .. "Fonts" .. pathsep .. "ARIALUNI.TTF"
    else
      font_file = "/usr/share/fonts/truetype/arphic/uming.ttc" - Linux path ?
    end
How path to Unicode Font on Android ?
http://code.google.com/p/corsix-th/issues/detail?id=1103 - This my instruction for Windows.

**Comment by matshch** [comment]
This problem is relevant again, game can't find a font. Nexus 5, Android 6.0.
