### ISSUE TITLE
Right Click on TF201 closes window

### ISSUE THREAD

**Issue by alanwoolley** [alanwoolley/CorsixTH-Android#46]
Unconfirmed report on Google Play Store that right clicking on Asus Transformer Prime closes the window.

**Comment by imachine** [comment]
This probably can be joined with my issue, https://github.com/alanwoolley/CorsixTH-Android/issues/105, due to the fact right click in Android also makes the "Back" symbol.

**Comment by alanwoolley** [comment]
Closing in favour of #105 which has more information & discussion.
