### ISSUE TITLE
Setup wizard always runs

### ISSUE THREAD

**Issue by alanwoolley** [alanwoolley/CorsixTH-Android#73]
Multiple reports by email of the setup wizard activity always launching. Pressing the 'play' button on the final page just restarts the activity.

Observed on Nexus 5 running 4.4.4 and SGS5 running 4.4.2 using both CD and GOG versions of Theme Hospital.

**Comment by antlangston** [comment]
This is exactly what is happening on my Galaxy Tab Pro 12.2. 

I've tried it with the files on the internal and external memory, I've also tried it with and without the hidden files. Nothing seems to make it work, it just keeps going round in a loop. :(

I look forward to your wizards working their magic and making this a reality for me... my childhood self will love you for all eternity.
