### ISSUE TITLE
Black Screen Samsung Galaxy Alpha

### ISSUE THREAD

**Issue by Asbowl2468** [alanwoolley/CorsixTH-Android#85]
Hey there i just bought th and ported it to corsix it knows where the game files are but it just runs with a black screen I can press buttons just can't see anything

Android 4.4

Cheers

**Comment by alanwoolley** [comment]
Is it an official version of Android or a custom ROM? Rooted / any modifications or apps that might interfere? Have you tried with the demo files instead?

**Comment by Asbowl2468** [comment]
Thanks for the reply is the official android 4.4.4 rooted,  as far as I'm aware I have no apps/mods that could interfere I've messed around with Dev options with no results and yes I've tried the demo same problem

**Comment by alanwoolley** [comment]
Thanks for the update. The only times I've seen this issue is when the device has been too old to support the required features, or a modification has been made to the system (usually as a "performance optimization") and has broken some required functionality.

As your phone is quite new and appears to have all the right features, it should be supported. I don't have a Galaxy Alpha myself to test this on, so I'd appreciate it if someone else could independently confirm this on theirs.

**Comment by PhilD85** [comment]
I'm experiencing the same (or similar issue) with my Galaxy Tab S. I point it to the files, and I'm presented with a black screen. If I double tap, sometimes I get the message "no quicksave to load" or I will get into the options (Run Setup Wizard, etc, etc.)

**Comment by alanwoolley** [comment]
@PhilD85 Your device should be perfectly capable. Are you running a custom rom or anything that might interfere with graphics? It seems as though the UI elements are there but just failing to be rendered.

**Comment by PhilD85** [comment]
Running official 5.0 ROM as auto updated, new tablet as of Saturday. Is
there any way to pull logs off the device or attach a debugger to help you
out? I am a software developer, just very little experience with Android.

**Comment by Chetic** [comment]
I'm having this issue too, on my Nexus 9. Only on the github version though. (Which is the same now as when I tried 3-4 months ago). I get the recent changes dialog every time, and if I modify SharedPreferences I can get it to run the wizard again, but after that it's all black. Scripts are never copied. If I download the Play Store version it runs fine, including copying scripts.

I was hoping to improve support for mouse devices, and I have debugging all set up so please let me know what I can do to provide further information! I can't figure out why, but it seems the main Activity (CTHApplication I think) never successfully starts. It just loops in some native Android code.

**Comment by ChristopheAlonso** [comment]
Same happening here with galaxy note 3 SN900 (mali). black screen on launch, even with the demo. but i'm able to open the menu by clicking the screen randomly and access: setup wizard/settings. Unfortunatly changing resolution or enything else is not helping...

**Comment by imachine** [comment]
Hi, confirm on Samsung Galaxy Tab S 10,5" with 5.0.2 stock Samsung Android OS, the game (todays version, tried to sign up for beta, but no update showed up) shows nothing but a black screen.

**Comment by alanwoolley** [comment]
Thanks for the reports. I've still not got much of an idea as to why this is occuring, so any more information you can provide would be really helpful. Particularly if there's any apps installed like Twilight or settings that have been changed which might affect graphics & UI.

I'm working on getting a version up and running using the new SDL2 renderering engine, which I hope may resolve this. I'll start publishing builds on to the alpha channel on Google Play in the next couple of weeks; I'll update this thread when they're ready.

**Comment by ChristopheAlonso** [comment]
You're welcome.
I'm suspecting the 5.0 lollipop Os to be involved in that problem.
Especially the Samsung rom. (Official rom by the way) Can't say more about
what might be lacking, but some of my oldies games seams to have the same
"black screen" problem after this upgrade (I noticed that with baldur's
gate which were working perfectly on kitkat but now have the same
problem... developers are making a working beta test on a new version after
being aware of that problem).
In the same time, "actual" games don't have any problem (I'm playing xcom
or telltale walking dead for exemple).

Unfortunatly i've tested corsixth on the lollipop Os only, so I don't know
if it has ever worked on kitkat or older.
Sorry that i'm not able to help you more with that.

For the record i'm on a Samsung Galaxy note3 sm-n900 with mali t-628
graphic processor under lollipop 5.0. I don't have twilight and didn't
tweak any graphic settings in any ways.

Anyway, thanks for trying to solve that probleme and for the hard work.

If I can help in any way let me know.

Christophe.

Thanks for the reports. I've still not got much of an idea as to why this
is occuring, so any more information you can provide would be really
helpful. Particularly if there's any apps installed like Twilight or
settings that have been changed which might affect graphics & UI.

I'm working on getting a version up and running using the new SDL2
renderering engine, which I hope may resolve this. I'll start publishing
builds on to the alpha channel on Google Play in the next couple of weeks;
I'll update this thread when they're ready.

—
Reply to this email directly or view it on GitHub
<https://github.com/alanwoolley/CorsixTH-Android/issues/85#issuecomment-118971717>
.

**Comment by alanwoolley** [comment]
Thanks for the update.

> Can't say more about
what might be lacking, but some of my oldies games seams to have the same
"black screen" problem after this upgrade (I noticed that with baldur's
gate which were working perfectly on kitkat but now have the same
problem... developers are making a working beta test on a new version after
being aware of that problem).

Do you know of any more instances like this, and can you point me towards the Baldur's Gate app you mention here? It might be useful to open a dialogue with them if I can't find a solution.

**Comment by ChristopheAlonso** [comment]
Sure!
The app is here:
https://play.google.com/store/apps/details?id=com.beamdog.baldursgateenhancededition&hl=fr

Andy ou might be able to join the developers team here:
http://forums.beamdog.com/discussion/40761/12311-bgii-ee-should-not-show-a-blank-screen-on-android-devices

And I think that beta test is here:
http://forums.beamdog.com/discussion/41975/android-update-beta-test-for-baldurs-gate-baldurs-gate-ii-and-icewind-dale#latest

Hope it will help.

Keep me in touch.

Christophe

Thanks for the update.

Can't say more about
what might be lacking, but some of my oldies games seams to have the same
"black screen" problem after this upgrade (I noticed that with baldur's
gate which were working perfectly on kitkat but now have the same
problem... developers are making a working beta test on a new version after
being aware of that problem).

Do you know of any more instances like this, and can you point me towards
the Baldur's Gate app you mention here? It might be useful to open a
dialogue with them if I can't find a solution.

—
Reply to this email directly or view it on GitHub
<https://github.com/alanwoolley/CorsixTH-Android/issues/85#issuecomment-119145480>
.

**Comment by imachine** [comment]
I can confirm the app works fine on Samsung Galaxy A3 with stock 4.4.4 KitKat Rom. 

The lollipop update is on its way so as it comes I'll check to see if CorsixTH stops working then.

**Comment by alanwoolley** [comment]
I've started making alpha builds for the next release and I'm hoping that one of the changes will have resolved this issue. I'd like to invite you to try it out and see if it works on your devices. Instructions are here: http://www.armedpineapple.co.uk/2013/05/beta-testing-corsixth-for-android/

If you'd prefer, there are apks that you can manually install here: http://www.armedpineapple.co.uk/cth/android/

**Comment by ChristopheAlonso** [comment]
Thanks Alan.
It had launched the demo and I can see the menu now! Thanks for the good
work!
